name:                raytracer
version:             2.6.2.0
github:              "eijian/raytracer"
license:             BSD3
author:              eijian
maintainer:          akagi.eiji@gmail.com
copyright:           "Copyright (c) 2015, eijian"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Ray Tracing by Haskell
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Ray tracing program supported 'photon mapping' (GitHub at <https://github.com/eijian/raytracer>)

dependencies:
- base >= 4.8 && < 5

library:
  source-dirs: src

executables:
  # Photon Map generator
  pm:
    main:                Main-pm.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -Wall
    dependencies:
    #- raytracer
    - containers
    - numeric-prelude >= 0.4.2
    - random
    - mersenne-random >= 1.0
    - QuickCheck
    - kdt
    - text
    - vector
    - parsec
    - parsec-numbers
    - deepseq >=1.3
    - deepseq-generics >=0.1.1.1

  # Ray Tracer with Photon Mapping
  rt:
    main:                Main-rt.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    #- raytracer
    - containers
    - numeric-prelude >= 0.4.2
    - random
    - mersenne-random >= 1.0
    - QuickCheck
    - kdt
    - text
    - vector
    - parsec
    - parsec-numbers
    - deepseq >=1.3
    - deepseq-generics >=0.1.1.1

  # Ray Tracer with Photon Mapping
  rtc:
    main:                Main-rtc.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    #- raytracer
    - containers
    - numeric-prelude >= 0.4.2
    - random
    - mersenne-random >= 1.0
    - QuickCheck
    - kdt
    - text
    - vector
    - parsec
    - parsec-numbers
    - deepseq >=1.3
    - deepseq-generics >=0.1.1.1

  # Photon Map Converter
  pm2img:
    main:                Main-pm2img.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    #- raytracer
    - containers
    - numeric-prelude >= 0.4.2
    - random
    - mersenne-random >= 1.0
    - QuickCheck
    - kdt
    - text
    - vector
    - parsec
    - parsec-numbers
    - deepseq >=1.3
    - deepseq-generics >=0.1.1.1

tests:
  raytracer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raytracer
