(* EBNF definition: Scene *)
(* cf. https://ja.wikipedia.org/wiki/EBNF *)

{

  world = { blankline } , lightspec-list ,
          { blankline } , material-list   ,
          { blankline } , surface-list    ,
          { blankline } , mapper-list     ,
          { blankline } , vertex-list     ,
          { blankline } , normal-vec-list ,
          { blankline } , object-list     ,
          { blankline } , scene           ,
          { blankline } ;


  lightspec-list = "lightspec" , separator , linefeed ,
                    lightspec-elem , { { linefeed } , lightspec-elem } ;

  lightspec-elem = elem-name           ,
                   color | temperature ,
                   radiosity           ,
                   directivity         ,
                   rad-est             ,
                   direction           ;

  color       = indent2 , "color"       , separator , float3    , linefeed ;
  temperature = indent2 , "temperature" , separator , float     , linefeed ;
  radiosity   = indent2 , "radiosity"   , separator , float     , linefeed ;
  directivity = indent2 , "directivity" , separator , float     , linefeed ;
  rad-est     = indent2 , "rad_est"     , separator , radestval , linefeed ;
  dir-flag    = indent2 , "direction"   , separator , inout     , linefeed ;

  radestval = "photon" | "formula" ;

  material-list = "material" , separator , linefeed ,
                  material , { { linefeed } , material } ;

  material-elem = elem-name     ,
                  albedo_diff   ,
                  scatterness   ,
                  metalness     ,
                  transmittance ,
                  ior           ,
                  albedo_spec   ;

  albedo_diff   = indent2 , "albedo_diff"   , separator , float3     , linefeed ;
  scatterness   = indent2 , "scatterness"   , separator , float      , linefeed ;
  metalness     = indent2 , "metalness"     , separator , float      , linefeed ;
  transmittance = indent2 , "transmittance" , separator , float3     , linefeed ;
  ior           = indent2 , "ior"           , separator , float3     , linefeed ;
  albedo_spec   = indent2 , "albedo_spec"   , separator , { float3 } , linefeed ;

  surface-list = "surface"    , separator , linefeed ,
                 surface-elem , { { linefeed } , surface-elem } ;

  surface-elem = elem-name  ,
                 roughness  ,
                 lightparam ;

  roughness = indent2 , "roughness" , separator , float          , linefeed ;
  light     = indent2 , "light"     , separator , { identifier } , linefeed ;

  mapper-list = "mapper" , separator , linefeed ,
                mapper , { { linefeed } , mapper } ;

  mapper-elem = elem-name ,
                mappertype | { { linefeed } , mappertype } ;

  mappertype = solid | checker

  solid = indent2 , "type" , separator , "solid" , linefeed ,
          indent2 , "map"  , separator , maptuple , linefeed ;

  checker = indent2 , "type"  , separator , "checker" , linefeed ,
            indent2 , "map1"  , separator , maptuple  , linefeed ,
            indent2 , "map2"  , separator , maptuple  , linefeed ,
            indent2 , "scale" , separator , float     , linefeed ;

  maptuple = "[" , { space } , identifier , { space } , "," ,
                   { space } , identifier , { space } , "]" ;

  vertex-list = "vertex" , separator , linefeed ,
                vector-elem , { vector-elemx }  ;

  normal-vec-list = "normalvec" , separator , linefeed ,
                    vector-elem , { vector-elem }      ;

  vector-elem = indent2 , "-" , { space } , float3 , linefeed ;

  object-list = "object" , separator , linefeed ,
                object , { { linefeed } , object } ;

  object = elem-name ,
           oshape    ,
           omapper   ;

  oshape = plain | sphere | polygon | parallelogram | mesh ;

  plain = indent2 , "type"     , separator , "plain" , linefeed ,
          indent2 , "normal"   , separator , vector3 , linefeed ,
          indent2 , "position" , separator , vector3 , linefeed ;

  sphere = indent2 , "type"   , separator , "sphere" , linefeed ,
           indent2 , "center" , separator , vector3  , linefeed ,
           indent2 , "radius" , separator , float    , linefeed ;
  
  polygon = indent2 , "type" , separator , "polygon" , linefeed ,
            indent2 , "pos1" , separator , vector3   , linefeed ,
            indent2 , "pos2" , separator , vector3   , linefeed ,
            indent2 , "pos3" , separator , vector3   , linefeed ,

  parallelogram = indent2 , "type" , separator , "parallelogram" , linefeed ,
                  indent2 , "pos1" , separator , vector3         , linefeed ,
                  indent2 , "pos2" , separator , vector3         , linefeed ,
                  indent2 , "pos3" , separator , vector3         , linefeed ;

  mesh = indent2 , "type"    , separator , "mesh"   , linefeed ,
         indent2 , "polygon" , separator ,            linefeed ,
         polygon-elem , { polygon-elem }                      ;

  polygon-elem = indent2 , indent2 , "-" , { space } , "[" , { space } ,
                 vertex-info , { space } , "," , { space } ,
                 vertex-info , { space } , "," , { space } ,
                 vertex-info , { space } ,
                 "]" , linefeed ;
  
  vertex-info = "[" , { space } , posint , { space } , "," , { space } , posint , { space } , "," , { space } , posint , { space } , "]" ;
 
  omapper = indent2 , "mapper" , separator , identifier , linefeed ;

  scene = "scene" , separator , linefeed ,
          scene-elem , { scene-elem }    ;

  scene-elem = indent , "- " , identifier , linefeed ;

  elem-name = indent , identifier, separator , linefeed ;
  identifier = ( "_" } , letter , { "_" | "-" | letter | digit }
  indent2    = indent , indent ;
  indent     = '\0x20' , '\0x20' ;
  separator  = { space } , ":" , space ;

  inout  = "in" | "out" ;
  yesno  = "yes" | "no" ;
  filter = "none" | "cone" | "gauss" ;
  vector3 = float3 ;
  float3 = "[" , { space } , float , { space } , "," , { space } , float , {space} , "," , { space } , float , { space } , "]"
  float  = ( digit1 , { digit } ) | ( "-" , { digit } , digit) , [ "." , { digit } ] ;
  posint = digit , { digit } ;
  number = [ digit1 ] , { digit } , digit ;
  digit  = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
  digit1 = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
  letter = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" |
           "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" |
           "u" | "v" | "w" | "x" | "y" | "z" |
           "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" |
           "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" |
           "U" | "V" | "W" | "X" | "Y" | "Z" ;

  blankline = linefeed ;
  space = whitespace , { whitespace } ;
  whitespace = '\x20' | '\x09' ;
  linefeed = { whitespace } , '\x0a' | ( '\x0d' , '\x0a' ) ;

}
